@baseUrl = http://localhost:4000/api

### Registration
POST {{baseUrl}}/registration
Content-Type: application/json

{
	"email": "blacklacost3@gmail.com",
	"password": "123"
}

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
	"email": "blacklacost@gmail.com",
	"password": "qwe"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiYmxhY2tsYWNvc3RAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjU3NjkyMTI4LCJleHAiOjE2NTc2OTU3Mjh9.nWQjxcqcmRnvGJVAWNSF6l8FJXIk5IwhruxHKxlpRUU